services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend
  #     - gateway  # Uncommented this
  #   networks:
  #     - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    env_file:
      - frontend/.env
    command: npm start
    working_dir: /app/frontend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
      - /app/backend/venv
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    command: /app/venv/bin/gunicorn -w 2 -k uvicorn.workers.UvicornWorker --forwarded-allow-ips="*" -b 0.0.0.0:8000 main:app --reload
    working_dir: /app/backend
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "5055:5055"
    # Use the same path structure as your working supervisor setup
    command: ["/app/gateway/bin/run.sh", "root/conf.yaml"]
    working_dir: /app/gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge