version: '3.8'
services:
  web:
    build: .
    image: moonmarket-ibkr-api
    container_name: moonmarket
    ports:
      - "80:80"
      - "5055:5055"
      - "5056:5056"
    env_file:
      - backend/.env    # Use the same .env file
    # volumes:
    #  - backend/:/app/webapp